version: "3.9"
services:
  pg:
    image: postgres:16
    container_name: pg-identity
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
    ports:
      - "40001:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: redis-identity
    ports:
      - "40002:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pg_data: